# Numpy exercises

## Question 1
Write a program that takes n vectors of m elements from the user, calculates the distances 
between the vectors and a randomly generated m-element vector, and prints the minimum 
distance as the output.

In [23]:
import numpy as np
n = eval(input('enter number of vectors'))
m = eval(input('enter number of elements'))
vectorList = [] # from user

for i in range(n):
    vec = eval(input(f'enter vector{i + 1} of {m} elements'))
    while len(vec) < m or len(vec) > m:
        vec = eval(input(f'try again.\n enter vector{i + 1} of {m} elements'))
    vectorList.append(vec)
print(vectorList)  
        
        

def vectorGenerator(size=m, r=(0, 10), dtype='int'):
    '''input:   size: number of elements
                   r: random numbres between this range
               dtype: type of the elemnts
       output:      a vector - np array
       '''
    if dtype=='int':
        return np.random.randint(low=r[0], high=r[1], size=(1, size))
    np.random.uniform(size=m, low=r[0], high=r[1]) 
    


# calculating Euclidean distance
# using linalg.norm()
def euclideanDistance(veclst, singleVec):
    '''
    input:       veclst: list of vectors
              singleVec: a vector 
    output:     eucDist: dictionary with distances between singleVec and vectors in the list
    '''
    eucDist = {}
    for v_i, vec_i in enumerate(veclst):
        eucDist[(v_i, 'randomVec')] = np.linalg.norm(vec_i - singleVec)
    return eucDist

randomVec = vectorGenerator(size=m)
print('random vector',randomVec)
eucDist = euclideanDistance(veclst=vectorList, singleVec=randomVec)
print('result:\n', eucDist)

enter number of vectors 2
enter number of elements 2
enter vector1 of 2 elements 1,2
enter vector2 of 2 elements 2,3


[(1, 2), (2, 3)]
random vector [[9 7]]
result:
 {(0, 'randomVec'): 9.433981132056603, (1, 'randomVec'): 8.06225774829855}


# Question 2
Read the IASBS photo from your system and apply the following changes to it:
<code>
A- Change the type of photo array to 64float.
B- Color the IASBS photo completely blue.
C- Divide the photo into four equal parts.
D- Select one of the previous four parts and convert the photo to negative.
e- Select and save a part of the photo of step d as desired.
F- Print the photo dimensions saved in the previous step and their type.
</code>

In [24]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray

In [25]:
# A-
# load the image and convert into
# numpy array
path = 'IASBS.jpg'
name = path.split('.')[0]
img = Image.open('IASBS.jpg')

# asarray() class is used to convert
# PIL images into NumPy arrays

npImg = asarray(img)
# answer:
npImg_float = np.array(npImg, dtype=float)
# data type
print(npImg.dtype)
print(npImg_float.dtype)
#### reference:
#### https://www.geeksforgeeks.org/how-to-convert-images-to-numpy-array/

uint8
float64


In [26]:
# B-
npImg_copy = npImg.copy()
npImg_copy = asarray(npImg_copy)
npImg_copy[:, :, 0] = npImg_copy[:,:,0] * 0
npImg_copy[:, :, 1] = npImg_copy[:,:,1] * 0
npImg_copy[:, :, 2] = npImg_copy[:,:,2] * 255
save_b = Image.fromarray(npImg_copy, "RGB")
save_b.save(f'numpyExercise_part2_B_{name}.png')

In [27]:
# C
# first split width to 2 parts
axis_0 = np.split(npImg, 2)
splitted = []
# then split each parts to 2 from height 
for _slice in axis_0:
    splitted = splitted + np.split(_slice, 2, axis=1)
# reformat & save
for index, _slice in enumerate(splitted):
    # img = _slice.astype(np.uint8)
    img = Image.fromarray(_slice, "RGB")
    img.save(f'numpyExercise_part2_C_{name}_{index}.png')

In [28]:
# D-E
# for example
_slice_0 = splitted[0]
# multiply datas by -1
negative = _slice_0 * -1
# convert to uint8 type
img = negative.astype(np.uint8)
# convert array
img = Image.fromarray(img, "RGB")
img.save(f'numpyExercise_part2_D_{name}.png')

In [29]:
# F-
path_sliced = 'numpyExercise_part2_C_IASBS_1.png'
img_sliced = Image.open(path_sliced)
print(img_sliced.size)
print(asarray(img_sliced).dtype)

(1632, 1224)
uint8


## Question 3
Write a NumPy program to create a 5x5 array sequentially with numbers from 1 to 25. Swap the first and last columns and the second and third columns to create a new array from the given array.

In [30]:
# def matrixGenerator(size=(5, 5), r=(1, 25)):
#     return np.random.randint(low=r[0], high=r[1], size=size)
def matrix(r=(1, 25), shape=(5, 5)):
    '''inputs: r: tuple - range of numbers
           shape: tuple - shape of matrix
       output: matrix'''
    lst = np.array([i for i in range(r[0], r[1] + 1)])
    return np.reshape(lst, shape)

shape = (5, 5)
first = 1
second = 2
third = 3
last = 5
mat = matrix(shape=shape)
mat_copy = mat.copy()
# reference: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-150.php
mat_copy[:,[first - 1, last - 1]] = mat_copy[:,[last - 1, first - 1]]
mat_copy[:,[second - 1, third - 1]] = mat_copy[:,[third - 1, second - 1]]
# mat_copy[:,0], mat_copy[:,-1] = mat_copy[:,-1], mat_copy[:,0]
# mat_copy[:,1], mat_copy[:,2] = mat_copy[:,2], mat_copy[:,1]

print('Orginal:')
print(mat)
print('Swapped:')
print(mat_copy)

Orginal:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Swapped:
[[ 5  3  2  4  1]
 [10  8  7  9  6]
 [15 13 12 14 11]
 [20 18 17 19 16]
 [25 23 22 24 21]]


#### Question 4
Generate two vectors with the following elements:

x: [2, 4, 6]

y: [30, 40, 50]

Calculate and display their inner product, outer product, and cross product.

##### output
<code>Iner product of x and y:
 520
Outer product of x and y:
 [[ 60  80 100]
 [120 160 200]
 [180 240 300]]
Cross product of x and y:
 [-40  80 -40]</code>

In [31]:
import numpy as np
x = np.array([2, 4, 6])
y = np.array([30, 40, 50])
inner = np.inner(x, y)
outer = np.outer(x, y)
cross = np.cross(x, y)
print('Iner product of x and y:\n', inner)
print('Outer product of x and y:\n', outer)
print('Cross product of x and y:\n', cross)

Iner product of x and y:
 520
Outer product of x and y:
 [[ 60  80 100]
 [120 160 200]
 [180 240 300]]
Cross product of x and y:
 [-40  80 -40]


#### Question 5
Write a program that first receives the dimensions of the matrix and then the elements of the matrix from the user check the invertible of the matrix using Numpy and calculate the inverse of the matrix if it is invertible.

In [32]:
from numpy.linalg import inv
import numpy as np
#### from user
row, col = eval(input("Enter (Row, column) size"))
# row = 4
# col = 4
dim = (row, col)
#### elemnets from user
elements = []
for r in range(row):
    vec = eval(input(f'Enter {col} elements of row {r + 1}:\t'))
    while len(vec) < col or len(vec) > col:
        vec = eval(input(f'Try again.\nEnter {col} elements of row {r + 1}:\t'))
    elements.append(vec)

# elements = [[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]]
mat = np.array(elements)

def inverse(mat):
    '''
    Get a numpy array and return an inverse of it.'''
    try:
        return inv(mat)
    except np.linalg.LinAlgError as err:
        if 'Singular matrix' in str(err):
            return 'matrix determinant is 0. not invertible'
    else:
        raise
        
inverse(mat=mat)

Enter (Row, column) size 2,2
Enter 2 elements of row 1:	 2,3
Enter 2 elements of row 2:	 1,-2


array([[ 0.28571429,  0.42857143],
       [ 0.14285714, -0.28571429]])